# conda env create -f environment.yml
# conda env update -f environment.yml --prune

name: flycast-prism-editor
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - tk=*=xft_*
  - numpy
  - pillow
  - pip
  - pip:
    - customtkinter
    - platformdirs
    - openimageio
    - imageio
    - cexprtk
    - PyYAML